# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/Project/XILINX/sin_wave_add_v12/an9767_test.runs/synth_1/design_1_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param general.usePosixSpawnForFork 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Project/XILINX/sin_wave_add_v12/an9767_test.cache/wt [current_project]
set_property parent.project_path D:/Project/XILINX/sin_wave_add_v12/an9767_test.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions disable [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files D:/Project/XILINX/sin_wave_add_v12/sin1024.coe
read_verilog -library xil_defaultlib {
  D:/Project/XILINX/sin_wave_add_v12/an9767_test.srcs/sources_1/new/ad9238_driver.v
  D:/Project/XILINX/sin_wave_add_v12/an9767_test.srcs/sources_1/new/iir_biquad.v
  D:/Project/XILINX/sin_wave_add_v12/an9767_test.srcs/sources_1/new/peak_detector.v
  D:/Project/XILINX/sin_wave_add_v12/an9767_test.srcs/sources_1/new/sweep_controller.v
  D:/Project/XILINX/sin_wave_add_v12/an9767_test.srcs/sources_1/new/ad9767_test.v
  D:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/hdl/design_1_wrapper.v
}
read_ip -quiet D:/Project/XILINX/sin_wave_add_v12/an9767_test.srcs/sources_1/ip/PLL/PLL.xci
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/ip/PLL/PLL_board.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/ip/PLL/PLL.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/ip/PLL/PLL_ooc.xdc]

read_ip -quiet D:/Project/XILINX/sin_wave_add_v12/an9767_test.srcs/sources_1/ip/ROM/ROM.xci
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/ip/ROM/ROM_ooc.xdc]

add_files D:/Project/XILINX/sin_wave_add_v12/an9767_test.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_2_0/design_1_axi_gpio_2_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_2_0/design_1_axi_gpio_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_3_0/design_1_axi_gpio_3_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_3_0/design_1_axi_gpio_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_1/bd_6f02_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_2/bd_6f02_arinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_3/bd_6f02_rinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_4/bd_6f02_awinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_5/bd_6f02_winsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_6/bd_6f02_binsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_7/bd_6f02_aroutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_8/bd_6f02_routsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_9/bd_6f02_awoutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_10/bd_6f02_woutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_11/bd_6f02_boutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_12/bd_6f02_arni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_13/bd_6f02_rni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_14/bd_6f02_awni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_15/bd_6f02_wni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_16/bd_6f02_bni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_20/bd_6f02_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_21/bd_6f02_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_22/bd_6f02_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_23/bd_6f02_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_24/bd_6f02_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_25/bd_6f02_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_26/bd_6f02_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_27/bd_6f02_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_28/bd_6f02_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_29/bd_6f02_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_30/bd_6f02_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_31/bd_6f02_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_33/bd_6f02_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_34/bd_6f02_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_35/bd_6f02_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_36/bd_6f02_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_37/bd_6f02_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_38/bd_6f02_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_40/bd_6f02_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_41/bd_6f02_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_42/bd_6f02_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_43/bd_6f02_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_44/bd_6f02_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_45/bd_6f02_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_47/bd_6f02_m03s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_48/bd_6f02_m03arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_49/bd_6f02_m03rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_50/bd_6f02_m03awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_51/bd_6f02_m03wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_52/bd_6f02_m03bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/smartconnect.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_50M_1/design_1_rst_ps7_0_50M_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/design_1_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Project/XILINX/sin_wave_add_v12/an9767_test.srcs/constrs_1/new/ad9767.xdc
set_property used_in_implementation false [get_files D:/Project/XILINX/sin_wave_add_v12/an9767_test.srcs/constrs_1/new/ad9767.xdc]

read_xdc D:/Project/XILINX/sin_wave_add_v12/an9767_test.srcs/constrs_1/new/ad9238.xdc
set_property used_in_implementation false [get_files D:/Project/XILINX/sin_wave_add_v12/an9767_test.srcs/constrs_1/new/ad9238.xdc]

read_xdc D:/Project/XILINX/sin_wave_add_v12/an9767_test.srcs/constrs_1/new/key.xdc
set_property used_in_implementation false [get_files D:/Project/XILINX/sin_wave_add_v12/an9767_test.srcs/constrs_1/new/key.xdc]

read_xdc D:/Project/XILINX/sin_wave_add_v12/an9767_test.srcs/constrs_1/new/led.xdc
set_property used_in_implementation false [get_files D:/Project/XILINX/sin_wave_add_v12/an9767_test.srcs/constrs_1/new/led.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental D:/Project/XILINX/sin_wave_add_v12/an9767_test.srcs/utils_1/imports/synth_1/ad9767_test.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top design_1_wrapper -part xc7z020clg400-2
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
