# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ad9767.xdc

# XDC: new/ad9238.xdc

# XDC: new/key.xdc

# XDC: new/led.xdc

# IP: ip/ROM/ROM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ROM || ORIG_REF_NAME==ROM} -quiet] -quiet

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ad9767_test_2_0/design_1_ad9767_test_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ad9767_test_2_0 || ORIG_REF_NAME==design_1_ad9767_test_2_0} -quiet] -quiet

# IP: ip/PLL/PLL.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PLL || ORIG_REF_NAME==PLL} -quiet] -quiet

# IP: ip/ROM/ROM.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ROM || ORIG_REF_NAME==ROM} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_0/design_1_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_0 || ORIG_REF_NAME==design_1_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_1_0 || ORIG_REF_NAME==design_1_axi_gpio_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_2_0/design_1_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_2_0 || ORIG_REF_NAME==design_1_axi_gpio_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_3_0/design_1_axi_gpio_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_3_0 || ORIG_REF_NAME==design_1_axi_gpio_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_smc_1/design_1_axi_smc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_smc_1 || ORIG_REF_NAME==design_1_axi_smc_1} -quiet] -quiet

# Block Designs: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/bd_6f02.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_1/bd_6f02_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_2/bd_6f02_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_3/bd_6f02_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_4/bd_6f02_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_5/bd_6f02_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_6/bd_6f02_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_7/bd_6f02_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_8/bd_6f02_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_9/bd_6f02_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_10/bd_6f02_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_11/bd_6f02_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_12/bd_6f02_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_13/bd_6f02_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_14/bd_6f02_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_15/bd_6f02_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_16/bd_6f02_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_17/bd_6f02_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_18/bd_6f02_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_19/bd_6f02_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_20/bd_6f02_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_21/bd_6f02_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_22/bd_6f02_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_23/bd_6f02_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_24/bd_6f02_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_25/bd_6f02_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_26/bd_6f02_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_27/bd_6f02_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_28/bd_6f02_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_29/bd_6f02_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_30/bd_6f02_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_31/bd_6f02_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_32/bd_6f02_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_33/bd_6f02_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_34/bd_6f02_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_35/bd_6f02_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_36/bd_6f02_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_37/bd_6f02_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_38/bd_6f02_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_39/bd_6f02_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_40/bd_6f02_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_41/bd_6f02_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_42/bd_6f02_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_43/bd_6f02_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_44/bd_6f02_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_45/bd_6f02_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_46/bd_6f02_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_47/bd_6f02_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_48/bd_6f02_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_49/bd_6f02_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_50/bd_6f02_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_51/bd_6f02_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_52/bd_6f02_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_53/bd_6f02_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_rst_ps7_0_50M_1/design_1_rst_ps7_0_50M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_50M_1 || ORIG_REF_NAME==design_1_rst_ps7_0_50M_1} -quiet] -quiet

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/ip/ROM/ROM_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/ip/ROM/ROM_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_1_0 || ORIG_REF_NAME==design_1_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_2_0/design_1_axi_gpio_2_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_2_0 || ORIG_REF_NAME==design_1_axi_gpio_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_2_0/design_1_axi_gpio_2_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_3_0/design_1_axi_gpio_3_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_3_0 || ORIG_REF_NAME==design_1_axi_gpio_3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_3_0/design_1_axi_gpio_3_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_1/bd_6f02_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_2/bd_6f02_arinsw_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_3/bd_6f02_rinsw_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_4/bd_6f02_awinsw_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_5/bd_6f02_winsw_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_6/bd_6f02_binsw_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_7/bd_6f02_aroutsw_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_8/bd_6f02_routsw_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_9/bd_6f02_awoutsw_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_10/bd_6f02_woutsw_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_11/bd_6f02_boutsw_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_12/bd_6f02_arni_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_13/bd_6f02_rni_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_14/bd_6f02_awni_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_15/bd_6f02_wni_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_16/bd_6f02_bni_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_20/bd_6f02_s00a2s_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_21/bd_6f02_sarn_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_22/bd_6f02_srn_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_23/bd_6f02_sawn_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_24/bd_6f02_swn_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_25/bd_6f02_sbn_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_26/bd_6f02_m00s2a_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_27/bd_6f02_m00arn_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_28/bd_6f02_m00rn_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_29/bd_6f02_m00awn_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_30/bd_6f02_m00wn_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_31/bd_6f02_m00bn_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_33/bd_6f02_m01s2a_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_34/bd_6f02_m01arn_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_35/bd_6f02_m01rn_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_36/bd_6f02_m01awn_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_37/bd_6f02_m01wn_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_38/bd_6f02_m01bn_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_40/bd_6f02_m02s2a_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_41/bd_6f02_m02arn_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_42/bd_6f02_m02rn_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_43/bd_6f02_m02awn_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_44/bd_6f02_m02wn_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_45/bd_6f02_m02bn_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_47/bd_6f02_m03s2a_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_48/bd_6f02_m03arn_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_49/bd_6f02_m03rn_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_50/bd_6f02_m03awn_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_51/bd_6f02_m03wn_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_52/bd_6f02_m03bn_0_ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/ooc.xdc

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_smc_1 || ORIG_REF_NAME==design_1_axi_smc_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_50M_1/design_1_rst_ps7_0_50M_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_50M_1 || ORIG_REF_NAME==design_1_rst_ps7_0_50M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Project/XILINX/sin_wave_add_v12/an9767_test.gen/sources_1/bd/design_1/design_1_ooc.xdc
