# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/stega/Desktop/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.srcs/sources_1/ip/sin_rom_1024x14/sin_rom_1024x14.xci
# IP: The module: 'sin_rom_1024x14' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/stega/Desktop/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/ip/sin_rom_1024x14/sin_rom_1024x14_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sin_rom_1024x14'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/stega/Desktop/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.srcs/sources_1/ip/sin_rom_1024x14/sin_rom_1024x14.xci
# IP: The module: 'sin_rom_1024x14' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/stega/Desktop/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/ip/sin_rom_1024x14/sin_rom_1024x14_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sin_rom_1024x14'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
