# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.srcs/sources_1/ip/adc_pll_65M/adc_pll_65M.xci
# IP: The module: 'adc_pll_65M' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/ip/adc_pll_65M/adc_pll_65M_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_pll_65M'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/ip/adc_pll_65M/adc_pll_65M.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_pll_65M'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/ip/adc_pll_65M/adc_pll_65M_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_pll_65M'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.srcs/sources_1/ip/adc_pll_65M/adc_pll_65M.xci
# IP: The module: 'adc_pll_65M' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/ip/adc_pll_65M/adc_pll_65M_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_pll_65M'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/ip/adc_pll_65M/adc_pll_65M.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_pll_65M'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/ip/adc_pll_65M/adc_pll_65M_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_pll_65M'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
