# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/key.xdc

# XDC: new/ad9238.xdc

# XDC: new/led.xdc

# XDC: new/da9767.xdc

# IP: ip/tri_rom_1024x14/tri_rom_1024x14.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tri_rom_1024x14 || ORIG_REF_NAME==tri_rom_1024x14} -quiet] -quiet

# Block Designs: bd/zynq_system/zynq_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_system || ORIG_REF_NAME==zynq_system} -quiet] -quiet

# IP: bd/zynq_system/ip/zynq_system_processing_system7_0_0/zynq_system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_system_processing_system7_0_0 || ORIG_REF_NAME==zynq_system_processing_system7_0_0} -quiet] -quiet

# IP: bd/zynq_system/ip/zynq_system_top_system_0_0/zynq_system_top_system_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_system_top_system_0_0 || ORIG_REF_NAME==zynq_system_top_system_0_0} -quiet] -quiet

# IP: ip/sin_rom_1024x14/sin_rom_1024x14.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sin_rom_1024x14 || ORIG_REF_NAME==sin_rom_1024x14} -quiet] -quiet

# IP: ip/adc_pll_65M/adc_pll_65M.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_pll_65M || ORIG_REF_NAME==adc_pll_65M} -quiet] -quiet

# IP: ip/tri_rom_1024x14/tri_rom_1024x14.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tri_rom_1024x14 || ORIG_REF_NAME==tri_rom_1024x14} -quiet] -quiet

# IP: bd/zynq_system/ip/zynq_system_axi_dma_0_0/zynq_system_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_system_axi_dma_0_0 || ORIG_REF_NAME==zynq_system_axi_dma_0_0} -quiet] -quiet

# IP: bd/zynq_system/ip/zynq_system_axi_gpio_0_0/zynq_system_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_system_axi_gpio_0_0 || ORIG_REF_NAME==zynq_system_axi_gpio_0_0} -quiet] -quiet

# IP: bd/zynq_system/ip/zynq_system_axi_gpio_1_0/zynq_system_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_system_axi_gpio_1_0 || ORIG_REF_NAME==zynq_system_axi_gpio_1_0} -quiet] -quiet

# IP: bd/zynq_system/ip/zynq_system_axi_gpio_2_0/zynq_system_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_system_axi_gpio_2_0 || ORIG_REF_NAME==zynq_system_axi_gpio_2_0} -quiet] -quiet

# IP: bd/zynq_system/ip/zynq_system_axi_smc_0/zynq_system_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_system_axi_smc_0 || ORIG_REF_NAME==zynq_system_axi_smc_0} -quiet] -quiet

# Block Designs: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/bd_5e13.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_1/bd_5e13_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_2/bd_5e13_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_3/bd_5e13_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_4/bd_5e13_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_5/bd_5e13_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_6/bd_5e13_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_7/bd_5e13_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_8/bd_5e13_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_9/bd_5e13_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_10/bd_5e13_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_11/bd_5e13_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_12/bd_5e13_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_13/bd_5e13_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_14/bd_5e13_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_15/bd_5e13_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_16/bd_5e13_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_17/bd_5e13_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_18/bd_5e13_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_19/bd_5e13_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_20/bd_5e13_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_21/bd_5e13_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_22/bd_5e13_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_23/bd_5e13_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_24/bd_5e13_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_25/bd_5e13_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_26/bd_5e13_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_27/bd_5e13_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_28/bd_5e13_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_29/bd_5e13_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_30/bd_5e13_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_31/bd_5e13_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_32/bd_5e13_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_33/bd_5e13_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_34/bd_5e13_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_35/bd_5e13_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_36/bd_5e13_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_37/bd_5e13_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_38/bd_5e13_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_39/bd_5e13_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_40/bd_5e13_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_41/bd_5e13_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_42/bd_5e13_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_43/bd_5e13_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_44/bd_5e13_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_45/bd_5e13_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_46/bd_5e13_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_47/bd_5e13_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_48/bd_5e13_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_49/bd_5e13_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_50/bd_5e13_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_51/bd_5e13_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_52/bd_5e13_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_53/bd_5e13_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/zynq_system/ip/zynq_system_rst_ps7_0_50M_0/zynq_system_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_system_rst_ps7_0_50M_0 || ORIG_REF_NAME==zynq_system_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/zynq_system/ip/zynq_system_axi_mem_intercon_imp_auto_pc_0/zynq_system_axi_mem_intercon_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_system_axi_mem_intercon_imp_auto_pc_0 || ORIG_REF_NAME==zynq_system_axi_mem_intercon_imp_auto_pc_0} -quiet] -quiet

# IP: bd/zynq_system/ip/zynq_system_axi_mem_intercon_imp_auto_us_0/zynq_system_axi_mem_intercon_imp_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_system_axi_mem_intercon_imp_auto_us_0 || ORIG_REF_NAME==zynq_system_axi_mem_intercon_imp_auto_us_0} -quiet] -quiet

# IP: bd/zynq_system/ip/zynq_system_axi_mem_intercon_0/zynq_system_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_system_axi_mem_intercon_0 || ORIG_REF_NAME==zynq_system_axi_mem_intercon_0} -quiet] -quiet

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_processing_system7_0_0/zynq_system_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_system_processing_system7_0_0 || ORIG_REF_NAME==zynq_system_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_dma_0_0/zynq_system_axi_dma_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_system_axi_dma_0_0 || ORIG_REF_NAME==zynq_system_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_dma_0_0/zynq_system_axi_dma_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_system_axi_dma_0_0 || ORIG_REF_NAME==zynq_system_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_gpio_0_0/zynq_system_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_system_axi_gpio_0_0 || ORIG_REF_NAME==zynq_system_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_gpio_0_0/zynq_system_axi_gpio_0_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_gpio_1_0/zynq_system_axi_gpio_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_system_axi_gpio_1_0 || ORIG_REF_NAME==zynq_system_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_gpio_1_0/zynq_system_axi_gpio_1_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_gpio_2_0/zynq_system_axi_gpio_2_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_system_axi_gpio_2_0 || ORIG_REF_NAME==zynq_system_axi_gpio_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_gpio_2_0/zynq_system_axi_gpio_2_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_1/bd_5e13_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_2/bd_5e13_arinsw_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_3/bd_5e13_rinsw_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_4/bd_5e13_awinsw_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_5/bd_5e13_winsw_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_6/bd_5e13_binsw_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_7/bd_5e13_aroutsw_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_8/bd_5e13_routsw_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_9/bd_5e13_awoutsw_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_10/bd_5e13_woutsw_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_11/bd_5e13_boutsw_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_12/bd_5e13_arni_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_13/bd_5e13_rni_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_14/bd_5e13_awni_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_15/bd_5e13_wni_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_16/bd_5e13_bni_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_20/bd_5e13_s00a2s_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_21/bd_5e13_sarn_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_22/bd_5e13_srn_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_23/bd_5e13_sawn_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_24/bd_5e13_swn_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_25/bd_5e13_sbn_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_26/bd_5e13_m00s2a_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_27/bd_5e13_m00arn_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_28/bd_5e13_m00rn_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_29/bd_5e13_m00awn_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_30/bd_5e13_m00wn_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_31/bd_5e13_m00bn_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_33/bd_5e13_m01s2a_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_34/bd_5e13_m01arn_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_35/bd_5e13_m01rn_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_36/bd_5e13_m01awn_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_37/bd_5e13_m01wn_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_38/bd_5e13_m01bn_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_40/bd_5e13_m02s2a_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_41/bd_5e13_m02arn_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_42/bd_5e13_m02rn_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_43/bd_5e13_m02awn_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_44/bd_5e13_m02wn_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_45/bd_5e13_m02bn_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_47/bd_5e13_m03s2a_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_48/bd_5e13_m03arn_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_49/bd_5e13_m03rn_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_50/bd_5e13_m03awn_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_51/bd_5e13_m03wn_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/bd_0/ip/ip_52/bd_5e13_m03bn_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_smc_0/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_system_axi_smc_0 || ORIG_REF_NAME==zynq_system_axi_smc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_rst_ps7_0_50M_0/zynq_system_rst_ps7_0_50M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_system_rst_ps7_0_50M_0 || ORIG_REF_NAME==zynq_system_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_mem_intercon_imp_auto_pc_0/zynq_system_axi_mem_intercon_imp_auto_pc_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_mem_intercon_imp_auto_us_0/zynq_system_axi_mem_intercon_imp_auto_us_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_system_axi_mem_intercon_imp_auto_us_0 || ORIG_REF_NAME==zynq_system_axi_mem_intercon_imp_auto_us_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/ip/zynq_system_axi_mem_intercon_imp_auto_us_0/zynq_system_axi_mem_intercon_imp_auto_us_0_ooc.xdc

# XDC: c:/Users/stega/Desktop/vibeFPGA/example1_wave_read_v7/example1_wave_read_v3/example1_wave_read_v1.gen/sources_1/bd/zynq_system/zynq_system_ooc.xdc
